### ISSUE TITLE
Crash on loading / creating a world

### ISSUE THREAD

**Issue by lnminh1411** [jellysquid3/Sodium#1999]
### Bug Description

Minecraft Startup is fine
No mods conflict
No missing libs

Applied to both Sodium 0.4.10 and 0.5.0 on Minecraft version 1.20.1

### Reproduction Steps

Open any worlds or create a new world

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12329629/latest.log)

### Crash Report

[crash-2023-08-13_20.26.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12329625/crash-2023-08-13_20.26.01-client.txt)

**Comment by hexadecimal233** [comment]
Update wilder wild should fix this.

**Comment by CreeperVN2484** [comment]
Every mods is already in the lastest version (at least i checked with both cursedforge and modrinth)

**Comment by lnminh1411** [comment]
> Update wilder wild should fix this.

Checked with both modrinth and cursedforge app, all mods are updated
Also wilder wild 2.1.2 do fix compatibility issue

**Comment by pajicadvance** [comment]
Some of your mods require Indium, but you don't have it installed. You are also using the mod Hold That Chunk which is known for causing a memory leak.

**Comment by lnminh1411** [comment]
> Some of your mods require Indium, but you don't have it installed. You are also using the mod Hold That Chunk which is known for causing a memory leak.

Installed Indium, still does not work, also updated sodium to 0.5.0 and other things to support it

Updated logs and crash file:

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12329706/latest.log)
[crash-2023-08-13_21.17.32-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12329708/crash-2023-08-13_21.17.32-client.txt)

**Comment by pajicadvance** [comment]
The mod "Sodium Occlusion Culling Fix" is no longer needed starting from Sodium 0.5. Besides that, none of the other errors in the log have anything to do with Sodium.
