### ISSUE TITLE
The models in Immersive Engineering don't have smooth lighting.

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2828]
### Bug Description

![2024-10-21_13 55 38](https://github.com/user-attachments/assets/954b7b07-47a2-43c5-ab12-230c5ad8f3d9)
![2024-10-21_13 48 33](https://github.com/user-attachments/assets/22de92d1-ec3e-4e20-8ae8-04705c476d08)
![2024-10-21_13 48 38](https://github.com/user-attachments/assets/ceee4362-f111-48c6-ac04-8446d9207148)

### Reproduction Steps

Place an Immersive Engineering machine
See the bug

### Log File

https://mclo.gs/rdD42wD

### Crash Report

*

**Comment by jellysquid3** [comment]
Is this fixed with https://github.com/CaffeineMC/sodium/commit/0bc026109506e9d442439d713eaf5a9d97a71ed0?

**Comment by Lolothepro** [comment]
> Is this fixed with [0bc0261](https://github.com/CaffeineMC/sodium/commit/0bc026109506e9d442439d713eaf5a9d97a71ed0)?

no

**Comment by Redls07** [comment]
What is this mechanism in the screenshots?
I wanted to test it, but I can't find a way to get it.

**Comment by Lolothepro** [comment]
[dsed.zip](https://github.com/user-attachments/files/29142317/dsed.zip)
load this world
and it's not fixed

**Comment by Redls07** [comment]
Are you sure this is a Sodium bug? I can reproduce this issue without it, only with Immersive Engineering.

**Comment by Lolothepro** [comment]
> Are you sure this is a Sodium bug? I can reproduce this issue without it, only with Immersive Engineering.

You need to enable the experimental lighting pipeline in the NeoForge settings
