### ISSUE TITLE
Switching to Fullscreen Resets GUI Scale Option

### ISSUE THREAD

**Issue by douira** [jellysquid3/Sodium#3381]
A user has reported that when they switch to fullscreen, the GUI Scale option gets reset to "Auto" (the default value). I cannot reproduce this, but my suspicion is that it does this because during the fullscreen transition it briefly changes the resolution to a value smaller than the current non-auto gui scale is appropriate for, so it gets reset.

This also happens when a user starts their game in fullscreen (or what I assume must be fullscreen?). See https://github.com/CaffeineMC/sodium/issues/3399

**Comment by pesegolsson** [comment]
for me it does this sometimes, not every time, but it does reset to auto every time i quit/start the game so I have to change it when i start the game which is a tad annoying. all other settings seams to stay (i've ticked/unticked so many check boxes this morning to check!)

**Comment by zChenX1** [comment]
> for me it does this sometimes, not every time, but it does reset to auto every time i quit/start the game so I have to change it when i start the game which is a tad annoying. all other settings seams to stay (i've ticked/unticked so many check boxes this morning to check!)

same... that so annoying

**Comment by quEyZy** [comment]
Samer here I can reproduce the problem all the time. (Sodium 0.8.0 for Fabric 1.21.11).
Always sets the GUI to automatic instead of what I set it to, whenever i start the game new

**Comment by douira** [comment]
Please direct additional reports of this bug at our discord server unless you have a new insight to share.

**Comment by derklaro** [comment]
For me the value also resets when I start the game. This seems to be caused by the initial reset introduced with the new config handling. I play on gui scale 3 and my games starts with an initial resolution of 854x480, resulting in a max gui scale of 2. After resizing (maximizing) the window to 2560x1369 a new max gui scale of 5 is calculated which allows me to set the option to 3 again. So a workaround for now seems to be to start with a bigger initial resolution.

**Comment by NewMagnet** [comment]
The problem also exists on "brightness" though I don't need to care about it because of gamma override

**Comment by douira** [comment]
> The problem also exists on "brightness" though I don't need to care about it because of gamma override

Are you using the gamma mod? There was a separate issue that has since been resolved by that mod in an update.

**Comment by NewMagnet** [comment]
> > The problem also exists on "brightness" though I don't need to care about it because of gamma override
> 
> Are you using the gamma mod? There was a separate issue that has since been resolved by that mod in an update.

Actually none of tweakeroo's business haha.Just tell that the brightness setting also has problems

**Comment by douira** [comment]
It's unclear what you mean by that. Please make a new issue and explain the situation and give a reproduction. Otherwise this report is unactionable.

**Comment by douira** [comment]
Please test this build and let me know whether it fixes the issue for you: https://nightly.link/CaffeineMC/sodium/actions/runs/20216162869/sodium-artifacts-.zip **Use no other mods in combination with this!**
If it does not, send your gamelog AND a video of the problem.
you can also come to [our discord server](https://jellysquid.me/discord) to discuss the build here: https://discord.com/channels/602796788608401408/1449606946255802534

**Comment by pesegolsson** [comment]
> Please test this build and let me know whether it fixes the issue for you: https://nightly.link/CaffeineMC/sodium/actions/runs/20216162869/sodium-artifacts-.zip If it does not, send your gamelog AND a video of the problem. you can also come to [our discord server](https://jellysquid.me/discord) to discuss the build here: https://discord.com/channels/602796788608401408/1449606946255802534

well, it seems to have fixed the gui scale, but i can't enter the video settings and do changes in this version, clicking the "Video Settings... button does nothing. so testing it properly isn't a thing i can do!

**Comment by douira** [comment]
you must be using another mod that is interfering. Please only use this build of sodium to test and send us a gamelog if the problem persists.

**Comment by pesegolsson** [comment]
yeah, it was a test version of voxy mod that disabled the video setting(forgot i added it). ran just fabric api and sodium, now the gui scale gets reset to 2x everytime i restart the game with startup resolution at "automatic". if i set it to 1280x720 it works fine and remembers the settings!

[latest.log](https://github.com/user-attachments/files/24195051/latest.log)

**Comment by douira** [comment]
Getting reset to 2x if that's the highest it can go given the resolution seems like the right behavior? or is this still different from how it was on vanilla/ sodium 0.7?

**Comment by derklaro** [comment]
I just tested Vanilla, and the gui scale option does not reset when I start the game with a resolution that is invalid for the option. It remains set to 3.

**Comment by pesegolsson** [comment]
yes the highest it can go is 2x in the startup resolution, but in vanilla fullscreen/maximized windows if you set it to 3x, restart the game in automatic resolution and go fullscreen after the game has started it remebers that the gui scale was set to 3x!

**Comment by douira** [comment]
I have made more changes and it should now work better. Please try it out! https://nightly.link/CaffeineMC/sodium/actions/runs/20278882151/sodium-artifacts-.zip

**Comment by pesegolsson** [comment]
that seem to have fixed it!  thank you and your team for putting down so much time making this mod!

**Comment by douira** [comment]
> caused my game to crash whenever I rendered falling gravel.

Please send us your crash log.

**Comment by Termina-1** [comment]
My mistake, it seems to happen regardless of if it's the snapshot mod or not. I just tried uninstalling and switching to the regular Sodium build and it still crashed from falling gravel. Here are both of the crash logs:

[crash-2025-12-17_07.16.08-client.txt](https://github.com/user-attachments/files/24214172/crash-2025-12-17_07.16.08-client.txt)
[crash-2025-12-17_07.29.11-client.txt](https://github.com/user-attachments/files/24214173/crash-2025-12-17_07.29.11-client.txt)

**Comment by douira** [comment]
It appears you are trying to use a mod that requires Fabric Rendering API even though it has not yet been released.

**Comment by Termina-1** [comment]
Ah that's probably the issue, thank you. I'm using the Prism launcher and auto updated all the mods and it said the Fabric Rendering API was one of them, but I didn't check to see it was properly updated.

**Comment by douira** [comment]
You can fix the issue by downgrading FAPI to before 0.140.0

**Comment by Termina-1** [comment]
That worked, thank you!

**Comment by Metaanie-afk** [comment]
>

**Comment by Metaanie-afk** [comment]
Ok
