### ISSUE TITLE
Tiny lag spikes when crossing chunk borders. 

### ISSUE THREAD

**Issue by QPCrummer** [jellysquid3/Sodium#462]
I recently made a bug report for this on starlight’s GitHub page. The dev told me that it wasn’t a server-side problem, but most likely a rendering problem. That is why I am making this report as Sodium is the mod I use for rendering. This has been happening for about 3 months now, and the people on my server are getting annoyed about it. I am a redstoner and this bug has caused a few issues with moving players with pistons. The over world is by far the worst for lagging. The nether is a close second, however it only lags sometimes. The end has zero chunk lag, probably due to the void. I know this is a widespread issue, but I am fairly sure that you can find some way around it. (:

**Comment by NoComment1105** [comment]
This was an issue in the 0.6.0 of phosphor, and was fixed in 0.7.0, someone correct if wrong

**Comment by QPCrummer** [comment]
It wasn’t fixed for me at least.

**Comment by QPCrummer** [comment]
SpottedLeaf said it wasn’t a lightning glitch, but a rendering problem.

**Comment by QPCrummer** [comment]
It was originally a lighting problem, but since I use starlight, which is a entirely new lighting engine, that problem would be gone. However, since the lighting part of it is fixed, the rendering part still exists.

**Comment by QPCrummer** [comment]
Instead of me explaining it, here is spottedleaf’s response: **From the performance numbers I've seen locally, in my experience it's actually just the rendering of these new chunks being loaded in that's causing spikes. While I want to fix issues like these, if it's not caused by the lightengine I really can't do anything from starlight.**

**Comment by NoComment1105** [comment]
oh whoops sorry

**Comment by jokbon** [comment]
old anoying vanila client bug, and those lagspikes not tiny but can last 5 seconds

**Comment by QPCrummer** [comment]
I know what it is, but I didn’t know it had to do with rendering chunks. I thought using a different lighting engine would fix it, but it didn’t. It helped though. I have a decent computer. Radeon RX 480 with a Ryzen FX 8530. It is very annoying

**Comment by QPCrummer** [comment]
After some further testing, I have concluded that Vanilla Minecraft Rendering lags for 1/4 of a second, Sodium lags for 1/2 of a second, and Optifine is also 1/2 however with Optifine it is very delayed, sometimes even close to 4 seconds of delay.

**Comment by QPCrummer** [comment]
Even with no other mods except for Sodium, Lithium, and Phosphor it still causes the chunk border lag.

**Comment by XfedeX** [comment]
Have you tryed to re-install Sodium and Fabric?

**Comment by ghost** [comment]
This bug is fixed on paper/tuinity servers

**Comment by QPCrummer** [comment]
That is actually not true. It is a hardware issue. I had an extremely old CPU and that was the problem. I upgraded to a 5950x and it works flawlessly now.

**Comment by jokbon** [comment]
Well this happens with ryzen 2700x which is not old cpu.

**Comment by whew-inc** [comment]
Also 2700x here with this issue

**Comment by maxomicbomb** [comment]
5600xt and ive got the problem to
