### ISSUE TITLE
Memory leak when loading chunks

### ISSUE THREAD

**Issue by fryman74** [jellysquid3/Sodium#773]
### Version information

1.17.1

### Expected Behavior

Since build 506, the memory leak issue when loading new chunks was supposed to be fixed.. Spoiler alert: it wasn't fixed! Even with just a bit of exploring, the RAM usage in Minecraft gets from 500MB average to 700MB! And it stays bigger and bigger forever, no matter what I tried! This was supposed to be fixed..

### Actual Behavior

Even with just a bit of exploring, the RAM usage in Minecraft gets from 500MB average to 700MB! And it stays bigger and bigger forever, no matter what I tried! This was supposed to be fixed..

### Reproduction Steps

(Don't know what to put here)

### Java version

Java 16

### CPU

Intel Pentium G4400

### GPU

Intel HD 510

### Additional information

I can't believe it.. Everyone was telling me it was supposed to be fixed since build 506... And today I tried the newest version with joy! At least until I noticed literally NOTHING changed about the RAM... I am very dissapointed!

**Comment by ItsTinay** [comment]
Try the newest official Sodium release

**Comment by fryman74** [comment]
@ItsTinay nope, it doesn't work.. still huge memory leak

**Comment by baturalp1337** [comment]
Yeah, they still not fix it. My game crashes too.

**Comment by Im-epics** [comment]
Damm came here to check if the leak was fixed.

**Comment by Altirix** [comment]
> I can't believe it.. Everyone was telling me it was supposed to be fixed since build 506... And today I tried the newest version with joy! At least until I noticed literally NOTHING changed about the RAM... I am very dissapointed!

well i bet the devs are very disappointed too that you haven't given them much to go off, the memory leak should be fixed, its wasnt even a sodium bug, it was a dependency in lwjgl that was supposed to be updated but wasnt so sodium has to now attempt to override it. sometimes that is just what happens.

complaining that "This was supposed to be fixed.." and being "very disappointed!" all I can say is, sir you ain't paying them. they are all volunteers. be patient. 

if you could provide them with as much useful information on this memory leak they might actually be able to solve it, but to everyone's knowledge that is currently fixed. ideally it needs to be replicated so people can test what will work to fix it.

**Comment by jellysquid3** [comment]
Upload a full client log file, and please don't spam my email to tell me how "disappointed" you are, and how you believe we mislead you. We thought this problem was fixed (as confirmed by dozens of volunteers and our own testing), but there may be additional issues causing memory leaks as well.

**Comment by jellysquid3** [comment]
Seeing 500-700 MB of additional memory usage outside of what you allocated to the game is *perfectly normal* and is exactly what vanilla does as well. We need to allocate memory outside the Java heap for graphics data and other things. There is only a memory leak here if the reported memory usage is continually increasing beyond that and never stops.

**Comment by fryman74** [comment]
That's exactly what happens. I load in new chunks and they never unload
from memory. Basically if I explore even a small distance, I get like even
200MB extra RAM used but the part here is that it never goes down! On
Minecraft Vanilla the RAM usage remains more consistent and fair and chunks
do unload, but when I use Sodium(which is the only mod that can help me
play the game good) my RAM goes higher and higher and higher and never
decreases even if I restart the game and stuff. This is normally not
supposed to happen. I can't even play the game because after I go like just
200 blocks in a direction, RAM gets from 500MB used to 600MB used and then
it gets bigger and bigger especially once I visit another dimension.

lun., 19 iul. 2021, 06:51 JellySquid ***@***.***> a scris:

**Comment by fryman74** [comment]
@Altirix You just shut up. I don't wanna hear you crying in my head. I am just a
simple dude and I was said that I was dissapointed because EVERYONE told me
it was fixed, not because I just read a bit about it and didn't think or
somethin'.
So please always read carefully! To explain a bit better, I was
dissapointed because I asked like a dozen people and they said it was fixed
and I just got super excited thinking that it was actually fixed, but then
I saw it wasn't fixed and I was just sad because those are people had no
problems

lun., 19 iul. 2021, 05:35 Altirix ***@***.***> a scris:

**Comment by fryman74** [comment]
And @jellysquid3
To explain a bit better, I was dissapointed because I asked like a dozen people and they said it was fixed and I just got super excited thinking that it was actually fixed, but then I saw it wasn't fixed and I was just sad because those are people had no problems

**Comment by jellysquid3** [comment]
I'm not here to entertain your attitude. Rather than providing the requested information you instead decide to argue and antagonize other users.

**Comment by jellysquid3** [comment]
We have sunk considerable time into debugging and fixing this issue, and we're fairly confident that the problem in resolved at this point. As mentioned earlier:

> Seeing 500-700 MB of additional memory usage outside of what you allocated to the game is perfectly normal and is exactly what vanilla does as well. We need to allocate memory outside the Java heap for graphics data and other things. There is only a memory leak here if the reported memory usage is continually increasing beyond that and never stops.

If another user is able to still reproduce this, please provide a client log file with the latest version of Sodium installed and ask for this issue to be re-opened.
